name: ReadMeGenerator
on:
  schedule: [{cron: "0 0 * * *"}]
  push:
    {branches: ["master", "main"]}
  pull_request:
    {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions: write-all
    
    
    steps:        
    #Base
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          repositories_forks: yes
          repositories_affiliations: ''
          base_indepth: yes
          users_ignored: no
          #extras_js: |
           # document.querySelectorAll("h2")?.forEach(h2 => h2.remove())
           

    #ISO Calendar
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          repositories_forks: yes
          repositories_affiliations: ''
          users_ignored: no
          plugin_isocalendar: yes


    #Starlists
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          repositories_forks: yes
          repositories_affiliations: ''
          users_ignored: no
          plugin_starlists: yes
          plugin_starlists_languages: yes


          
   #languages
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          repositories_forks: yes
          repositories_affiliations: ''
          users_ignored: no
          plugin_languages: yes
         # plugin_languages_ignored: >-
          #  html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
           # gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: no

          
          
    #Topics
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          repositories_forks: yes
          repositories_affiliations: ''
          users_ignored: no
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons  

          
    #Skyline     
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          repositories_forks: yes
          repositories_affiliations: ''
          users_ignored: no
          plugin_skyline: yes
          plugin_skyline_quality: 1
          plugin_skyline_year: 2024




          
